name: CI

on:
  pull_request:
    branches:
      - Assignment4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install CMake and build essentials, Doxygen and Xerces
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ make doxygen libxerces-c-dev valgrind

      - name: Build with AddressSanitizer
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS="-fsanitize=address" ..
          make

        #- name: Memory access error check
        # run: |
        #  cd build
        # ctest -T memcheck

      - name: Unit tests
        run: |
          cd build
          ctest --output-on-failure
